platform :ios, '7.0'
pod "AFNetworking", "~> 2.0"
pod 'MBProgressHUD', '~> 0.9.1'
pod 'Reachability', '~> 3.2'
pod 'FMDB', '~> 2.5'
platform :ios, '6.1'
pod 'SDWebImage', '~>3.7'
pod 'XMLReader', '~> 0.0.2'
